const doctorsData = [
  {
    id: "1",
    name: "Dr. John Smith",
    age: 45,
    specialty: "Cardiology",
    hospital: "New York General Hospital",
    status: "Available",
  },
  {
    id: "2",
    name: "Dr. Emily Johnson",
    age: 38,
    specialty: "Neurology",
    hospital: "London City Hospital",
    status: "Unavailable",
  },
  {
    id: "3",
    name: "Dr. Michael Brown",
    age: 50,
    specialty: "Pediatrics",
    hospital: "Sydney Children's Hospital",
    status: "Available",
  },
  {
    id: "4",
    name: "Dr. Sarah Davis",
    age: 40,
    specialty: "Orthopedics",
    hospital: "Tokyo Medical Center",
    status: "Unavailable",
  },
  {
    id: "5",
    name: "Dr. David Wilson",
    age: 55,
    specialty: "Gastroenterology",
    hospital: "Paris University Hospital",
    status: "Available",
  },
  {
    id: "6",
    name: "Dr. Jessica Moore",
    age: 36,
    specialty: "Dermatology",
    hospital: "Berlin Medical Center",
    status: "Available",
  },
  {
    id: "7",
    name: "Dr. Christopher Taylor",
    age: 47,
    specialty: "Ophthalmology",
    hospital: "Toronto Eye Institute",
    status: "Unavailable",
  },
  {
    id: "8",
    name: "Dr. Angela Anderson",
    age: 42,
    specialty: "Pulmonology",
    hospital: "Seoul National Hospital",
    status: "Available",
  },
  {
    id: "9",
    name: "Dr. Robert Martinez",
    age: 44,
    specialty: "Oncology",
    hospital: "Los Angeles Cancer Center",
    status: "Available",
  },
  {
    id: "10",
    name: "Dr. Mary Clark",
    age: 39,
    specialty: "Rheumatology",
    hospital: "Melbourne Medical Center",
    status: "Unavailable",
  },
  {
    id: "11",
    name: "Dr. James Thomas",
    age: 51,
    specialty: "Endocrinology",
    hospital: "San Francisco Health Center",
    status: "Available",
  },
  {
    id: "12",
    name: "Dr. Barbara Jackson",
    age: 46,
    specialty: "Urology",
    hospital: "Chicago Urology Clinic",
    status: "Unavailable",
  },
  {
    id: "13",
    name: "Dr. Daniel White",
    age: 52,
    specialty: "Nephrology",
    hospital: "Boston Kidney Institute",
    status: "Available",
  },
  {
    id: "14",
    name: "Dr. Patricia Harris",
    age: 43,
    specialty: "Allergy and Immunology",
    hospital: "Houston Medical Center",
    status: "Unavailable",
  },
  {
    id: "15",
    name: "Dr. Anthony Martin",
    age: 37,
    specialty: "Psychiatry",
    hospital: "Miami Mental Health Clinic",
    status: "Available",
  },
  {
    id: "16",
    name: "Dr. Linda Thompson",
    age: 48,
    specialty: "Radiology",
    hospital: "Philadelphia Radiology Institute",
    status: "Available",
  },
  {
    id: "17",
    name: "Dr. Richard Garcia",
    age: 49,
    specialty: "Anesthesiology",
    hospital: "Phoenix Surgical Center",
    status: "Unavailable",
  },
  {
    id: "18",
    name: "Dr. Elizabeth Martinez",
    age: 35,
    specialty: "Pathology",
    hospital: "Dallas Diagnostic Center",
    status: "Available",
  },
  {
    id: "19",
    name: "Dr. Steven Rodriguez",
    age: 41,
    specialty: "Hematology",
    hospital: "Washington Blood Institute",
    status: "Available",
  },
  {
    id: "20",
    name: "Dr. Susan Lewis",
    age: 39,
    specialty: "Infectious Disease",
    hospital: "Atlanta Infectious Disease Center",
    status: "Unavailable",
  },
];
export default doctorsData;
