// const scheduleData = [
//   // Dr. John Smith
//   {
//     date: "2024-10-01",
//     time: "08:00 - 09:00",
//     doctorId: "1",
//     patientId: "1",
//     content: "Hypertension checkup",
//     result: "Hypertension checkup",
//     status: "done",
//   },
//   {
//     date: "2024-10-05",
//     time: "09:00 - 10:00",
//     doctorId: "1",
//     patientId: "2",
//     content: "Heart disease management",
//     result: "Heart disease management",
//     status: "done",
//   },
//   {
//     date: "2024-10-10",
//     time: "14:00 - 15:00",
//     doctorId: "1",
//     patientId: "3",
//     content: "Blood pressure check",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Emily Johnson
//   {
//     date: "2024-10-02",
//     time: "10:00 - 11:00",
//     doctorId: "2",
//     patientId: "4",
//     content: "Neurology consultation",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Michael Brown
//   {
//     date: "2024-10-03",
//     time: "10:00 - 11:00",
//     doctorId: "3",
//     patientId: "3",
//     content: "Asthma management",
//     result: "Asthma management",
//     status: "done",
//   },
//   {
//     date: "2024-10-10",
//     time: "09:00 - 10:00",
//     doctorId: "3",
//     patientId: "5",
//     content: "Pediatric checkup",
//     result: "Pediatric checkup",
//     status: "done",
//   },

//   // Dr. Sarah Davis
//   {
//     date: "2024-10-05",
//     time: "09:00 - 10:00",
//     doctorId: "4",
//     patientId: "4",
//     content: "Migraine treatment",
//     result: "Migraine treatment",
//     status: "done",
//   },
//   {
//     date: "2024-10-12",
//     time: "13:00 - 14:00",
//     doctorId: "4",
//     patientId: "1",
//     content: "Orthopedic consultation",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. David Wilson
//   {
//     date: "2024-10-18",
//     time: "09:00 - 10:00",
//     doctorId: "5",
//     patientId: "5",
//     content: "Gastrointestinal treatment",
//     result: "Gastrointestinal treatment",
//     status: "done",
//   },
//   {
//     date: "2024-10-22",
//     time: "10:00 - 11:00",
//     doctorId: "5",
//     patientId: "2",
//     content: "Digestive health check",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Jessica Moore
//   {
//     date: "2024-10-25",
//     time: "08:00 - 09:00",
//     doctorId: "6",
//     patientId: "1",
//     content: "Dermatology check",
//     result: "Dermatology check",
//     status: "done",
//   },
//   {
//     date: "2024-10-30",
//     time: "11:00 - 12:00",
//     doctorId: "6",
//     patientId: "3",
//     content: "Skin condition check",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Christopher Taylor
//   {
//     date: "2024-10-08",
//     time: "10:00 - 11:00",
//     doctorId: "7",
//     patientId: "5",
//     content: "Ophthalmology check",
//     result: "Ophthalmology check",
//     status: "done",
//   },
//   {
//     date: "2024-10-15",
//     time: "13:00 - 14:00",
//     doctorId: "7",
//     patientId: "4",
//     content: "Eye test",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Angela Anderson
//   {
//     date: "2024-10-18",
//     time: "14:00 - 15:00",
//     doctorId: "8",
//     patientId: "2",
//     content: "Pulmonology consultation",
//     result: "Pulmonology consultation",
//     status: "done",
//   },
//   {
//     date: "2024-10-25",
//     time: "09:00 - 10:00",
//     doctorId: "8",
//     patientId: "1",
//     content: "Lung function test",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Robert Martinez
//   {
//     date: "2024-10-20",
//     time: "08:00 - 09:00",
//     doctorId: "9",
//     patientId: "3",
//     content: "Cancer screening",
//     result: "Cancer screening",
//     status: "done",
//   },
//   {
//     date: "2024-10-28",
//     time: "11:00 - 12:00",
//     doctorId: "9",
//     patientId: "5",
//     content: "Oncology follow-up",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Mary Clark
//   {
//     date: "2024-11-01",
//     time: "08:00 - 09:00",
//     doctorId: "10",
//     patientId: "5",
//     content: "Rheumatology checkup",
//     result: "Rheumatology checkup",
//     status: "done",
//   },
//   {
//     date: "2024-11-05",
//     time: "09:00 - 10:00",
//     doctorId: "10",
//     patientId: "4",
//     content: "Rheumatology follow-up",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. James Thomas
//   {
//     date: "2024-11-10",
//     time: "10:00 - 11:00",
//     doctorId: "11",
//     patientId: "2",
//     content: "Endocrinology follow-up",
//     result: "Endocrinology follow-up",
//     status: "done",
//   },
//   {
//     date: "2024-11-15",
//     time: "09:00 - 10:00",
//     doctorId: "11",
//     patientId: "3",
//     content: "Hormonal therapy review",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Barbara Jackson
//   {
//     date: "2024-11-20",
//     time: "09:00 - 10:00",
//     doctorId: "12",
//     patientId: "5",
//     content: "Urology checkup",
//     result: "Urology checkup",
//     status: "done",
//   },

//   // Dr. Daniel White
//   {
//     date: "2024-11-25",
//     time: "10:00 - 11:00",
//     doctorId: "13",
//     patientId: "1",
//     content: "Nephrology follow-up",
//     result: "Nephrology follow-up",
//     status: "done",
//   },

//   // Dr. Patricia Harris
//   {
//     date: "2024-10-12",
//     time: "09:00 - 10:00",
//     doctorId: "14",
//     patientId: "2",
//     content: "Immunology consultation",
//     result: "Immunology consultation",
//     status: "done",
//   },

//   // Dr. Anthony Martin
//   {
//     date: "2024-10-15",
//     time: "11:00 - 12:00",
//     doctorId: "15",
//     patientId: "4",
//     content: "Psychiatry session",
//     result: "Psychiatry session",
//     status: "done",
//   },

//   // Dr. Linda Thompson
//   {
//     date: "2024-10-20",
//     time: "09:00 - 10:00",
//     doctorId: "16",
//     patientId: "3",
//     content: "Radiology scan",
//     result: "Radiology scan",
//     status: "done",
//   },

//   // Dr. Richard Garcia
//   {
//     date: "2024-10-22",
//     time: "13:00 - 14:00",
//     doctorId: "17",
//     patientId: "2",
//     content: "Anesthesia consultation",
//     result: "unavailable",
//     status: "pending",
//   },

//   // Dr. Elizabeth Martinez
//   {
//     date: "2024-10-25",
//     time: "09:00 - 10:00",
//     doctorId: "18",
//     patientId: "1",
//     content: "Pathology report",
//     result: "Pathology report",
//     status: "done",
//   },

//   // Dr. Steven Rodriguez
//   {
//     date: "2024-11-01",
//     time: "14:00 - 15:00",
//     doctorId: "19",
//     patientId: "5",
//     content: "Hematology test",
//     result: "Hematology test",
//     status: "done",
//   },

//   // Dr. Susan Lewis
//   {
//     date: "2024-11-05",
//     time: "11:00 - 12:00",
//     doctorId: "20",
//     patientId: "4",
//     content: "Infectious disease consultation",
//     result: "unavailable",
//     status: "pending",
//   },
// ];
// export default scheduleData;

const scheduleData = [
  // Dr. John Smith (Cardiology)
  {
    id: "1",
    date: "2024-10-01",
    time: "08:00 - 09:00",
    doctorId: "1",
    patientId: "1",
    content: "Hypertension checkup",
    result: "Hypertension checkup",
    status: "cancel",
  },
  {
    id: "2",
    date: "2024-10-05",
    time: "09:00 - 10:00",
    doctorId: "1",
    patientId: "2",
    content: "Heart disease management",
    result: "Heart disease management",
    status: "done",
  },
  {
    id: "3",
    date: "2024-10-10",
    time: "14:00 - 15:00",
    doctorId: "1",
    patientId: "3",
    content: "Blood pressure check",
    result: "unavailable",
    status: "pending",
  },
  {
    id: "4",
    date: "2024-10-15",
    time: "11:00 - 12:00",
    doctorId: "1",
    patientId: "4",
    content: "Cardiology follow-up",
    result: "Cardiology consultation",
    status: "done",
  },
  {
    id: "5",
    date: "2024-10-20",
    time: "09:00 - 10:00",
    doctorId: "1",
    patientId: "5",
    content: "General heart check",
    result: "Heart checkup",
    status: "done",
  },

  // Dr. Emily Johnson (Neurology)
  {
    id: "6",
    date: "2024-10-02",
    time: "10:00 - 11:00",
    doctorId: "2",
    patientId: "1",
    content: "Neurology consultation",
    result: "unavailable",
    status: "cancel",
  },
  {
    id: "7",
    date: "2024-10-06",
    time: "13:00 - 14:00",
    doctorId: "2",
    patientId: "3",
    content: "Neurology consultation",
    result: "Migraine diagnosis",
    status: "done",
  },
  {
    id: "8",
    date: "2024-10-10",
    time: "11:00 - 12:00",
    doctorId: "2",
    patientId: "5",
    content: "Headache consultation",
    result: "Headache treatment",
    status: "done",
  },
  {
    id: "9",
    date: "2024-10-12",
    time: "14:00 - 15:00",
    doctorId: "2",
    patientId: "4",
    content: "Migraine consultation",
    result: "unavailable",
    status: "pending",
  },

  // Dr. Michael Brown (Pediatrics)
  {
    id: "10",
    date: "2024-10-03",
    time: "10:00 - 11:00",
    doctorId: "3",
    patientId: "1",
    content: "Pediatric checkup",
    result: "Asthma management",
    status: "done",
  },
  {
    id: "11",
    date: "2024-10-08",
    time: "11:00 - 12:00",
    doctorId: "3",
    patientId: "2",
    content: "Pediatric follow-up",
    result: "unavailable",
    status: "pending",
  },
  {
    id: "12",
    date: "2024-10-13",
    time: "09:00 - 10:00",
    doctorId: "3",
    patientId: "3",
    content: "Child health assessment",
    result: "Growth check",
    status: "done",
  },
  {
    id: "13",
    date: "2024-10-15",
    time: "10:00 - 11:00",
    doctorId: "3",
    patientId: "4",
    content: "Developmental assessment",
    result: "Development check",
    status: "done",
  },
  {
    id: "14",
    date: "2024-10-17",
    time: "09:00 - 10:00",
    doctorId: "3",
    patientId: "5",
    content: "General pediatric checkup",
    result: "General checkup",
    status: "done",
  },

  // Dr. Sarah Davis (Orthopedics)
  {
    id: "15",
    date: "2024-10-05",
    time: "09:00 - 10:00",
    doctorId: "4",
    patientId: "1",
    content: "Orthopedic consultation",
    result: "Joint pain consultation",
    status: "done",
  },
  {
    id: "16",
    date: "2024-10-12",
    time: "13:00 - 14:00",
    doctorId: "4",
    patientId: "2",
    content: "Back pain evaluation",
    result: "Back pain treatment",
    status: "done",
  },
  {
    id: "17",
    date: "2024-10-15",
    time: "11:00 - 12:00",
    doctorId: "4",
    patientId: "3",
    content: "Spine alignment check",
    result: "Spine evaluation",
    status: "done",
  },
  {
    id: "18",
    date: "2024-10-20",
    time: "10:00 - 11:00",
    doctorId: "4",
    patientId: "4",
    content: "Orthopedic surgery follow-up",
    result: "Post-surgery follow-up",
    status: "done",
  },
  {
    id: "19",
    date: "2024-10-25",
    time: "09:00 - 10:00",
    doctorId: "4",
    patientId: "5",
    content: "Knee replacement consultation",
    result: "unavailable",
    status: "pending",
  },

  // Dr. David Wilson (Gastroenterology)
  {
    id: "20",
    date: "2024-10-18",
    time: "09:00 - 10:00",
    doctorId: "5",
    patientId: "1",
    content: "Gastrointestinal checkup",
    result: "Gastric ulcer treatment",
    status: "done",
  },
  {
    id: "21",
    date: "2024-10-22",
    time: "10:00 - 11:00",
    doctorId: "5",
    patientId: "2",
    content: "Liver function test",
    result: "Liver evaluation",
    status: "done",
  },
  {
    id: "22",
    date: "2024-10-25",
    time: "09:00 - 10:00",
    doctorId: "5",
    patientId: "3",
    content: "Digestive system consultation",
    result: "Digestive health check",
    status: "done",
  },
  {
    id: "23",
    date: "2024-10-30",
    time: "11:00 - 12:00",
    doctorId: "5",
    patientId: "4",
    content: "Colonoscopy consultation",
    result: "unavailable",
    status: "pending",
  },
  {
    id: "24",
    date: "2024-11-01",
    time: "09:00 - 10:00",
    doctorId: "5",
    patientId: "5",
    content: "Gastroenterology follow-up",
    result: "Digestive disorder management",
    status: "done",
  },
];

export default scheduleData;
