const usersData = [
  {
    username: "john_doe",
    user_slug: "john-doe",
    password: "hashed_password_1",
    salt: "random_salt_1",
    email: "john_doe@example.com",
    phone: "0123456789",
    roleId: "1",
    firstName: "John",
    lastName: "Doe",
    dob: "1985-06-15",
    status: "ACTIVE",
    visibility: true,
  },
  {
    username: "dr_smith",
    user_slug: "dr-smith",
    password: "hashed_password_2",
    salt: "random_salt_2",
    email: "dr_smith@example.com",
    phone: "0987654321",
    roleId: "2",
    firstName: "Dr.",
    lastName: "Smith",
    dob: "1975-04-22",
    status: "ACTIVE",
    visibility: true,
  },
  {
    username: "jane_doe",
    user_slug: "jane-doe",
    password: "hashed_password_3",
    salt: "random_salt_3",
    email: "jane_doe@example.com",
    phone: "0111222333",
    roleId: "1",
    firstName: "Jane",
    lastName: "Doe",
    dob: "1990-01-01",
    status: "INACTIVE",
    visibility: false,
  },
  {
    username: "dr_mike",
    user_slug: "dr-mike",
    password: "hashed_password_4",
    salt: "random_salt_4",
    email: "dr_mike@example.com",
    phone: "0999888777",
    roleId: "2",
    firstName: "Mike",
    lastName: "Thompson",
    dob: "1980-12-12",
    status: "ACTIVE",
    visibility: true,
  },
  {
    username: "emma_watson",
    user_slug: "emma-watson",
    password: "hashed_password_5",
    salt: "random_salt_5",
    email: "emma_watson@example.com",
    phone: "0171789999",
    roleId: "1",
    firstName: "Emma",
    lastName: "Watson",
    dob: "1995-05-05",
    status: "ACTIVE",
    visibility: true,
  },
];

export default usersData;
